export type BreedOption = { slug: string; nameSv: string }

export const BREED_OPTIONS: BreedOption[] = [
  { slug: 'afghan_hound', nameSv: 'Afghansk vinthund' },
  { slug: 'airedale_terrier', nameSv: 'Airedaleterrier' },
  { slug: 'akita', nameSv: 'Akita' },
  { slug: 'alaskan_malamute', nameSv: 'Alaskan Malamute' },
  { slug: 'australian_kelpie', nameSv: 'Australisk kelpie' },
  { slug: 'australian_shepherd', nameSv: 'Australisk vallhund' },
  { slug: 'basset_hound', nameSv: 'Basset Hound' },
  { slug: 'beagle', nameSv: 'Beagle' },
  { slug: 'bedlington_terrier', nameSv: 'Bedlingtonterrier' },
  { slug: 'belgian_malinois', nameSv: 'Belgisk vallhund Malinois' },
  { slug: 'belgian_tervuren', nameSv: 'Belgisk vallhund Tervuren' },
  { slug: 'berger_australien', nameSv: 'Berger Australien' },
  { slug: 'bernese_mountain_dog', nameSv: 'Berner sennenhund' },
  { slug: 'bichon_frise', nameSv: 'Bichon Frisé' },
  { slug: 'bloodhound', nameSv: 'Blodhund' },
  { slug: 'border_collie', nameSv: 'Border Collie' },
  { slug: 'border_terrier', nameSv: 'Borderterrier' },
  { slug: 'borzoi', nameSv: 'Borzoj' },
  { slug: 'boston_terrier', nameSv: 'Bostonterrier' },
  { slug: 'bouvier_des_flandres', nameSv: 'Bouvier des Flandres' },
  { slug: 'boxer', nameSv: 'Boxer' },
  { slug: 'braque_francais', nameSv: 'Braque Français (Pyrénées)' },
  { slug: 'brittany', nameSv: 'Brittanyspaniel' },
  { slug: 'bullmastiff', nameSv: 'Bullmastiff' },
  { slug: 'bull_terrier', nameSv: 'Bullterrier' },
  { slug: 'cairn_terrier', nameSv: 'Cairnterrier' },
  { slug: 'cane_corso', nameSv: 'Cane Corso Italiano' },
  { slug: 'welsh_corgi_cardigan', nameSv: 'Cardigan Welsh Corgi' },
  { slug: 'cavalier_king_charles', nameSv: 'Cavalier King Charles Spaniel' },
  { slug: 'chesapeake_bay_retriever', nameSv: 'Chesapeake Bay retriever' },
  { slug: 'chihuahua', nameSv: 'Chihuahua' },
  { slug: 'chow_chow', nameSv: 'Chow Chow' },
  { slug: 'clumber_spaniel', nameSv: 'Clumberspaniel' },
  { slug: 'cocker_spaniel', nameSv: 'Cocker spaniel' },
  { slug: 'collie_smooth', nameSv: 'Collie (kort)' },
  { slug: 'collie_rough', nameSv: 'Collie (lång)' },
  { slug: 'dalmatian', nameSv: 'Dalmatiner' },
  { slug: 'dobermann', nameSv: 'Dobermann' },
  { slug: 'miniature_pinscher', nameSv: 'Dvärg-pinscher' },
  { slug: 'miniature_schnauzer', nameSv: 'Dvärg-schnauzer' },
  { slug: 'poodle_miniature', nameSv: 'Dvärgpudel' },
  { slug: 'dachshund_miniature', nameSv: 'Dvärgtax' },
  { slug: 'english_setter', nameSv: 'Engelsk setter' },
  { slug: 'springer_spaniel_english', nameSv: 'Engelsk springerspaniel' },
  { slug: 'finnish_lapphund', nameSv: 'Finsk lapphund' },
  { slug: 'flat_coated_retriever', nameSv: 'Flatcoated retriever' },
  { slug: 'french_bulldog', nameSv: 'Fransk bulldogg' },
  { slug: 'golden_retriever', nameSv: 'Golden Retriever' },
  { slug: 'gordon_setter', nameSv: 'Gordonsetter' },
  { slug: 'great_dane', nameSv: 'Grand danois' },
  { slug: 'greyhound', nameSv: 'Greyhound' },
  { slug: 'hamiltons_stovare', nameSv: 'Hamiltonsstövare' },
  { slug: 'havanese', nameSv: 'Havaneser' },
  { slug: 'dutch_shepherd', nameSv: 'Holländsk vallhund' },
  { slug: 'irish_red_setter', nameSv: 'Irländsk rödsätterhund' },
  { slug: 'irish_red_white_setter', nameSv: 'Irländsk rödvit setter' },
  { slug: 'icelandic_sheepdog', nameSv: 'Islandshund' },
  { slug: 'italian_greyhound', nameSv: 'Italiensk vinthund' },
  { slug: 'jack_russell_terrier', nameSv: 'Jack Russell Terrier' },
  { slug: 'dachshund_rabbit', nameSv: 'Kanintax' },
  { slug: 'wirehaired_pointing_griffon', nameSv: 'Korthals griffon' },
  { slug: 'curly_coated_retriever', nameSv: 'Krullig retriever' },
  { slug: 'labrador', nameSv: 'Labrador Retriever' },
  { slug: 'maltese', nameSv: 'Malteser' },
  { slug: 'mastiff', nameSv: 'Mastiff' },
  { slug: 'miniature_american_shepherd', nameSv: 'Miniature American Shepherd' },
  { slug: 'pug', nameSv: 'Mops' },
  { slug: 'newfoundland', nameSv: 'Newfoundlandshund' },
  { slug: 'norfolk_terrier', nameSv: 'Norfolkterrier' },
  { slug: 'norwegian_elkhound', nameSv: 'Norsk älghund grå' },
  { slug: 'norwich_terrier', nameSv: 'Norwichterrier' },
  { slug: 'nova_scotia_retriever', nameSv: 'Nova Scotia duck tolling retriever' },
  { slug: 'papillon', nameSv: 'Papillon' },
  { slug: 'parson_russell_terrier', nameSv: 'Parson Russell Terrier' },
  { slug: 'welsh_corgi_pembroke', nameSv: 'Pembroke Welsh Corgi' },
  { slug: 'pinscher', nameSv: 'Pinscher' },
  { slug: 'english_pointer', nameSv: 'Pointer' },
  { slug: 'pomeranian', nameSv: 'Pommeranian' },
  { slug: 'portuguese_water_dog', nameSv: 'Portugisisk vattenhund' },
  { slug: 'poodle_standard', nameSv: 'Pudel (stor)' },
  { slug: 'rhodesian_ridgeback', nameSv: 'Rhodesian ridgeback' },
  { slug: 'rottweiler', nameSv: 'Rottweiler' },
  { slug: 'saluki', nameSv: 'Saluki' },
  { slug: 'samoyed', nameSv: 'Samojed' },
  { slug: 'saint_bernard', nameSv: 'Sankt Bernhardshund' },
  { slug: 'schillerstovare', nameSv: 'Schillerstövare' },
  { slug: 'standard_schnauzer', nameSv: 'Schnauzer' },
  { slug: 'shetland_sheepdog', nameSv: 'Shetland sheepdog' },
  { slug: 'shiba', nameSv: 'Shiba' },
  { slug: 'shih_tzu', nameSv: 'Shih Tzu' },
  { slug: 'siberian_husky', nameSv: 'Sibirisk husky' },
  { slug: 'scottish_terrier', nameSv: 'Skotsk terrier' },
  { slug: 'smalandsstovare', nameSv: 'Smålandsstövare' },
  { slug: 'greater_swiss_mountain_dog', nameSv: 'Stor schweizisk sennenhund' },
  { slug: 'swedish_lapphund', nameSv: 'Svensk lapphund' },
  { slug: 'dachshund_standard', nameSv: 'Tax (normalstorlek)' },
  { slug: 'poodle_toy', nameSv: 'Toy pudel' },
  { slug: 'german_shorthaired_pointer', nameSv: 'Tysk korthårig vorsteh' },
  { slug: 'german_longhaired_pointer', nameSv: 'Tysk långhårig vorsteh' },
  { slug: 'german_shepherd', nameSv: 'Tysk schäfer' },
  { slug: 'hungarian_vizsla', nameSv: 'Ungersk vorsteh (Vizsla)' },
  { slug: 'swedish_vallhund', nameSv: 'Västgötaspets' },
  { slug: 'west_highland_white_terrier', nameSv: 'Västhighlandsterrier (Westie)' },
  { slug: 'weimaraner', nameSv: 'Weimaraner' },
  { slug: 'whippet', nameSv: 'Whippet' },
]

