export const CORE_PACKAGE_NAME = '@dogvantage/core'
export * from './types'
export * from './types/database'
export * from './types/api/schemas'
export * from './lib/utils/slugify'
export * from './lib/dog/age'
export * from './lib/dog/behavior'
export * from './lib/dog/build-behavior-context'
export * from './lib/dog/chat-topics'
export * from './lib/dog/timeline'
export * from './lib/training/allowed-exercises'
export * from './lib/training/assessment-week'
export * from './lib/training/day-scaler'
export * from './lib/training/decision-calibration'
export * from './lib/training/deterministic-week-planner'
export * from './lib/training/developmental-context'
export * from './lib/training/dog-state'
export * from './lib/training/exercise-label'
export * from './lib/training/exercise-specs'
export * from './lib/training/goal-exercises'
export * from './lib/training/handler-feedback'
export * from './lib/training/handler-state'
export * from './lib/training/homecoming-plan'
export * from './lib/training/insights'
export * from './lib/training/normalize-handler-guide'
export * from './lib/training/progression-kernel'
export * from './lib/training/puppy-zone'
export * from './lib/training/session-coach'
export * from './lib/training/skill-progress'
export * from './lib/training/streak'
export * from './lib/training/training-projects'
export * from './lib/training/week-context'
export * from './lib/training/week-plan-validator'
export * from './lib/training/rules'
export {
  computeProgressionDecisions,
  formatProgressionRule,
} from './lib/training/progression-rules'
export type { ExerciseProgressionDecision, ProgressionDecision } from './lib/training/progression-rules'
export * from './lib/training/weekly-focus'
